#ifndef SPRITE_IMAGES_H
#define SPRITE_IMAGES_H
#define sprite_index_alex_first 0
#define sprite_index_alex_count 20
#define sprite_index_alex_last 19
#define sprite_palette_alex 0
#define sprite_size_alex 0
#define sprite_pixelsize_alex 32
#define sprite_halfpixelsize_alex 16
#define sprite_index_arcadian_first 20
#define sprite_index_arcadian_count 16
#define sprite_index_arcadian_last 35
#define sprite_palette_arcadian 0
#define sprite_size_arcadian 0
#define sprite_pixelsize_arcadian 32
#define sprite_halfpixelsize_arcadian 16
#define sprite_index_ninjablack_first 36
#define sprite_index_ninjablack_count 16
#define sprite_index_ninjablack_last 51
#define sprite_palette_ninjablack 0
#define sprite_size_ninjablack 0
#define sprite_pixelsize_ninjablack 32
#define sprite_halfpixelsize_ninjablack 16
#define sprite_index_ninjared_first 52
#define sprite_index_ninjared_count 16
#define sprite_index_ninjared_last 67
#define sprite_palette_ninjared 0
#define sprite_size_ninjared 0
#define sprite_pixelsize_ninjared 32
#define sprite_halfpixelsize_ninjared 16
#define sprite_index_test_first 68
#define sprite_index_test_count 8
#define sprite_index_test_last 75
#define sprite_palette_test 2
#define sprite_size_test 0
#define sprite_pixelsize_test 32
#define sprite_halfpixelsize_test 16
#define sprite_index_hit_first 0
#define sprite_index_hit_count 1
#define sprite_index_hit_last 0
#define sprite_palette_hit 1
#define sprite_size_hit 1
#define sprite_pixelsize_hit 16
#define sprite_halfpixelsize_hit 8
#define sprite_index_test16_first 1
#define sprite_index_test16_count 8
#define sprite_index_test16_last 8
#define sprite_palette_test16 2
#define sprite_size_test16 1
#define sprite_pixelsize_test16 16
#define sprite_halfpixelsize_test16 8
#endif
