#ifndef SPRITE_IMAGES_H
#define SPRITE_IMAGES_H
#define sprite_index_alex_first 0
#define sprite_index_alex_count 24
#define sprite_index_alex_last 23
#define sprite_palette_alex 0
#define sprite_size_alex 0
#define sprite_pixelsize_alex 32
#define sprite_halfpixelsize_alex 16
#define sprite_index_arcadian_first 24
#define sprite_index_arcadian_count 16
#define sprite_index_arcadian_last 39
#define sprite_palette_arcadian 0
#define sprite_size_arcadian 0
#define sprite_pixelsize_arcadian 32
#define sprite_halfpixelsize_arcadian 16
#define sprite_index_ninjablack_first 40
#define sprite_index_ninjablack_count 20
#define sprite_index_ninjablack_last 59
#define sprite_palette_ninjablack 0
#define sprite_size_ninjablack 0
#define sprite_pixelsize_ninjablack 32
#define sprite_halfpixelsize_ninjablack 16
#define sprite_index_ninjared_first 60
#define sprite_index_ninjared_count 20
#define sprite_index_ninjared_last 79
#define sprite_palette_ninjared 0
#define sprite_size_ninjared 0
#define sprite_pixelsize_ninjared 32
#define sprite_halfpixelsize_ninjared 16
#define sprite_index_santa_first 80
#define sprite_index_santa_count 24
#define sprite_index_santa_last 103
#define sprite_palette_santa 0
#define sprite_size_santa 0
#define sprite_pixelsize_santa 32
#define sprite_halfpixelsize_santa 16
#define sprite_index_stroudman_first 104
#define sprite_index_stroudman_count 16
#define sprite_index_stroudman_last 119
#define sprite_palette_stroudman 0
#define sprite_size_stroudman 0
#define sprite_pixelsize_stroudman 32
#define sprite_halfpixelsize_stroudman 16
#endif
