#ifndef SPRITE_IMAGES_H
#define SPRITE_IMAGES_H
#define sprite_index_title_first 0
#define sprite_index_title_count 4
#define sprite_index_title_last 3
#define sprite_palette_title 2
#define sprite_size_title 0
#define sprite_index_asteroids_first 0
#define sprite_index_asteroids_count 8
#define sprite_index_asteroids_last 7
#define sprite_palette_asteroids 0
#define sprite_size_asteroids 1
#define sprite_index_explosions_first 8
#define sprite_index_explosions_count 8
#define sprite_index_explosions_last 15
#define sprite_palette_explosions 1
#define sprite_size_explosions 1
#define sprite_index_pickups_first 16
#define sprite_index_pickups_count 8
#define sprite_index_pickups_last 23
#define sprite_palette_pickups 1
#define sprite_size_pickups 1
#define sprite_index_pings_first 24
#define sprite_index_pings_count 8
#define sprite_index_pings_last 31
#define sprite_palette_pings 2
#define sprite_size_pings 1
#define sprite_index_player_first 32
#define sprite_index_player_count 4
#define sprite_index_player_last 35
#define sprite_palette_player 1
#define sprite_size_player 1
#define sprite_index_pointer_first 36
#define sprite_index_pointer_count 1
#define sprite_index_pointer_last 36
#define sprite_palette_pointer 2
#define sprite_size_pointer 1
#define sprite_index_trails_first 0
#define sprite_index_trails_count 4
#define sprite_index_trails_last 3
#define sprite_palette_trails 1
#define sprite_size_trails 2
#endif
